local set_keymap = vim.keymap.set

set_keymap("n", "<C-p>", function()
	Snacks.picker.commands()
end, { desc = "Command palette" })
set_keymap("n", "<leader>ff", function()
	Snacks.picker.files()
end, { desc = "Find files" })
set_keymap("n", "<leader>fw", function()
	Snacks.picker.grep()
end, { desc = "Find text" })
set_keymap("n", "<leader>fb", function()
	Snacks.picker.buffers()
end, { desc = "Find buffers" })
set_keymap("n", "<leader>fs", function()
	Snacks.picker.lsp_symbols()
end, { desc = "Find document symbols" })
set_keymap("n", "<leader>fS", function()
	Snacks.picker.lsp_workspace_symbols()
end, { desc = "Find workspace symbols" })
set_keymap("n", "<leader>fo", function()
	Snacks.picker.recent()
end, { desc = "Find recent files" })
set_keymap("n", "<leader>fc", function()
	Snacks.picker.commands()
end, { desc = "Find commands" })
set_keymap("n", "<leader>gb", function()
	Snacks.picker.git_branches()
end, { desc = "Git branches" })
set_keymap("n", "<leader>gc", function()
	Snacks.picker.git_log()
end, { desc = "Git commits" })
set_keymap("n", "<leader>gs", function()
	Snacks.picker.git_status()
end, { desc = "Git status" })
