{
  inputs,
  lib,
  self,
  ...
}: let
  inherit (lib) generators;

  mkAstroPlugins = pkgs: let
    mkGitHubPlugin = {
      owner,
      repo,
      rev,
      hash,
    }:
      pkgs.vimUtils.buildVimPlugin {
        pname = repo;
        version = "unstable-${builtins.substring 0 7 rev}";
        src = pkgs.fetchFromGitHub {
          inherit owner repo rev hash;
        };
        doCheck = false;
      };
  in {
    astronvim = pkgs.vimUtils.buildVimPlugin {
      pname = "astronvim";
      version = "6";
      src = inputs.astronvim;
      doCheck = false;
    };

    astrocommunity = pkgs.vimUtils.buildVimPlugin {
      pname = "astrocommunity";
      version = "unstable";
      src = inputs.astrocommunity;
      doCheck = false;
    };

    betterEscape = mkGitHubPlugin {
      owner = "max397574";
      repo = "better-escape.nvim";
      rev = "199dcc2643dec5d8dbdab4ec672cf405224dcb3b";
      hash = "sha256-47j0FKQ74HXYHWuKgAlDioGFdYk/XxGU9Qswdd4Rnxw=";
    };

    chezmoi = mkGitHubPlugin {
      owner = "xvzc";
      repo = "chezmoi.nvim";
      rev = "4167bbec76f693f481a5243f1be521ff0ccf1a6d";
      hash = "sha256-5opzK6mBgIO80g/zV7iaN+jcdV/EK1O7wibWv2pv+y8=";
    };

    chezmoiVim = mkGitHubPlugin {
      owner = "alker0";
      repo = "chezmoi.vim";
      rev = "7a498ea65f658993237fb0469001bdf71f68cf94";
      hash = "sha256-LfvOhqiBAqVrNzTz7vNhg+lCisL2IqWItUn8ZB9bSDw=";
    };

    gopher = mkGitHubPlugin {
      owner = "olexsmir";
      repo = "gopher.nvim";
      rev = "27ba078f14dd39fcd5e8a57d7009cdd77450ebbb";
      hash = "sha256-tfagWNHlfCRQ0BMihFCubKgMUpp5QtFl91ja4/Y2/gI=";
    };

    schemastore = mkGitHubPlugin {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "73e89eb3e536a4dd8f991c963bd37189520c9919";
      hash = "sha256-64QPVE298/XHx+UZeuvh5GndxiLgzWn1WfLJLBeZJKQ=";
    };
  };
in {
  options.flake.neovimModules.astronvim = lib.mkOption {
    type = lib.types.deferredModule;
    default = {};
    description = "Nix-native AstroNvim configuration generated by nvf.";
  };

  config = {
    flake.neovimModules.astronvim = {pkgs, ...}: let
      inherit
        (mkAstroPlugins pkgs)
        astronvim
        astrocommunity
        betterEscape
        chezmoi
        chezmoiVim
        gopher
        schemastore
        ;
      p = pkgs.vimPlugins;
      grammarPackages = with p.nvim-treesitter.grammarPlugins; [
        bash
        c
        css
        diff
        dockerfile
        fish
        git_config
        gitignore
        gleam
        go
        gomod
        gosum
        gowork
        html
        javascript
        jsdoc
        json
        lua
        luap
        markdown
        markdown_inline
        nix
        python
        query
        ruby
        rust
        toml
        tsx
        typescript
        vim
        vimdoc
        yaml
      ];
      grammarQueryPackages = map (grammar: grammar.passthru.associatedQuery) grammarPackages;
      grammarBundle = pkgs.symlinkJoin {
        name = "nvim-treesitter-grammars";
        paths = grammarPackages ++ grammarQueryPackages;
      };
      treesitter = p.nvim-treesitter.withPlugins (_: grammarPackages);

      inline = generators.mkLuaInline;
      toLua = value: generators.toLua {} value;

      mkDirSpec = name: package: extra:
        {
          inherit name;
          dir = "${package}";
        }
        // extra;

      astroNvimOpts = {
        mapleader = " ";
        maplocalleader = ",";
        icons_enabled = true;
        pin_plugins = null;
        update_notifications = true;
      };

      astroCoreOpts = {
        features = {
          large_buf = {
            size = 1024 * 256;
            lines = 10000;
          };
          autopairs = true;
          cmp = true;
          diagnostics = {
            virtual_text = true;
            virtual_lines = false;
          };
          highlighturl = true;
          notifications = true;
        };

        diagnostics = {
          virtual_text = true;
          underline = true;
        };

        filetypes = {
          extension.bu = "yaml";
          filename.".foorc" = "fooscript";
          pattern.".*%.bu%.tmpl" = "yaml";
          pattern.".*/etc/foo/.*" = "fooscript";
        };

        options = {
          opt = {
            relativenumber = false;
            number = true;
            spell = false;
            signcolumn = "yes";
            wrap = true;
            updatetime = 1000;
          };
        };

        autocmds = {
          alpha_autostart = false;
          restore_session = [
            {
              event = "VimEnter";
              desc = "Restore previous directory session if Neovim opened with no arguments";
              nested = true;
              callback = inline ''
                function()
                  if vim.fn.argc(-1) == 0 then
                    require("resession").load(vim.fn.getcwd(), { dir = "dirsession", silence_errors = true })
                  end
                end
              '';
            }
          ];
          autosave = [
            {
              event = ["InsertLeave" "CursorHold" "CursorHoldI"];
              callback = inline ''
                function(args)
                  local buf = args.buf
                  if vim.api.nvim_buf_get_name(buf) ~= ""
                    and vim.bo[buf].modifiable
                    and vim.bo[buf].buftype == ""
                    and vim.bo[buf].modified
                  then
                    vim.api.nvim_buf_call(buf, function() vim.cmd "silent update" end)
                  end
                end
              '';
            }
          ];
        };

        mappings = {
          n = {
            "]b" = inline ''{ function() require("astrocore.buffer").nav(vim.v.count1) end, desc = "Next buffer" }'';
            "[b" = inline ''{ function() require("astrocore.buffer").nav(-vim.v.count1) end, desc = "Previous buffer" }'';
            "<Leader>bd" = inline ''              {
                            function()
                              require("astroui.status.heirline").buffer_picker(
                                function(bufnr) require("astrocore.buffer").close(bufnr) end
                              )
                            end,
                            desc = "Close buffer from tabline",
                          }'';
            "<C-p>" = inline ''{ function() require("snacks.picker").commands() end, desc = "Command Palette" }'';
          };
        };

        treesitter = {
          highlight = true;
          indent = true;
          auto_install = false;
          ensure_installed = [
            "bash"
            "css"
            "diff"
            "dockerfile"
            "fish"
            "git_config"
            "gitignore"
            "gleam"
            "go"
            "gomod"
            "gowork"
            "html"
            "javascript"
            "json"
            "jsonc"
            "lua"
            "markdown"
            "markdown_inline"
            "nix"
            "python"
            "ruby"
            "toml"
            "tsx"
            "typescript"
            "vim"
            "yaml"
          ];
        };
      };

      astroLspOpts = {
        features = {
          codelens = true;
          inlay_hints = true;
          semantic_tokens = true;
        };

        formatting = {
          format_on_save = {
            enabled = true;
            allow_filetypes = [];
            ignore_filetypes = ["python"];
          };
          disabled = [];
          timeout_ms = 1000;
        };

        servers = [
          "ansiblels"
          "astro"
          "autotools_ls"
          "bashls"
          "clangd"
          "clojure_lsp"
          "cmake"
          "cssls"
          "dockerls"
          "elixirls"
          "fish_lsp"
          "gleam"
          "glsl_analyzer"
          "gopls"
          "hls"
          "html"
          "jdtls"
          "jinja_lsp"
          "jsonls"
          "just"
          "kotlin_language_server"
          "lemminx"
          "lua_ls"
          "nixd"
          "ruby_lsp"
          "rust_analyzer"
          "sqls"
          "svelte"
          "taplo"
          "terraformls"
          "texlab"
          "tinymist"
          "ts_ls"
          "ty"
          "zls"
        ];

        on_attach = inline ''function(client, bufnr) end'';
      };

      astroUiOpts = {
        colorscheme = "catppuccin-frappe";
        highlights = {
          init = {};
          astrodark = {};
        };
        icons = {
          LSPLoading1 = "⠋";
          LSPLoading2 = "⠙";
          LSPLoading3 = "⠹";
          LSPLoading4 = "⠸";
          LSPLoading5 = "⠼";
          LSPLoading6 = "⠴";
          LSPLoading7 = "⠦";
          LSPLoading8 = "⠧";
          LSPLoading9 = "⠇";
          LSPLoading10 = "⠏";
        };
      };

      resessionOpts = {
        buf_filter = inline ''function(bufnr) return require("astrocore.buffer").is_restorable(bufnr) end'';
        tab_buf_filter = inline ''function(tabpage, bufnr) return vim.tbl_contains(vim.t[tabpage].bufs or {}, bufnr) end'';
        extensions = {
          astrocore = {
            enable_in_tab = true;
          };
        };
      };

      communityImports = map (path: {"import" = path;}) [
        "astrocommunity.pack.ansible"
        "astrocommunity.pack.bash"
        "astrocommunity.pack.chezmoi"
        "astrocommunity.pack.gleam"
        "astrocommunity.pack.go"
        "astrocommunity.pack.json"
        "astrocommunity.pack.lua"
        "astrocommunity.pack.nix"
        "astrocommunity.pack.python"
        "astrocommunity.pack.rust"
        "astrocommunity.pack.typescript"
        "astrocommunity.pack.yaml"
        "astrocommunity.recipes.heirline-vscode-winbar"
        "astrocommunity.recipes.neovide"
        "astrocommunity.colorscheme.catppuccin"
      ];

      pluginSpecs =
        [
          (mkDirSpec "AstroNvim" astronvim {
            version = "^6";
            import = "astronvim.plugins";
            opts = astroNvimOpts;
          })
          (mkDirSpec "astrocommunity" astrocommunity {})
          (mkDirSpec "astrocore" p.astrocore {opts = astroCoreOpts;})
          (mkDirSpec "astrolsp" p.astrolsp {opts = astroLspOpts;})
          (mkDirSpec "astroui" p.astroui {opts = astroUiOpts;})
          (mkDirSpec "astrotheme" p.astrotheme {})
          (mkDirSpec "aerial.nvim" p.aerial-nvim {})
          (mkDirSpec "ansible-vim" p.ansible-vim {})
          (mkDirSpec "better-escape.nvim" betterEscape {})
          (mkDirSpec "blink.cmp" p.blink-cmp {})
          (mkDirSpec "blink.compat" p.blink-compat {})
          (mkDirSpec "catppuccin" p.catppuccin-nvim {})
          (mkDirSpec "chezmoi.nvim" chezmoi {})
          (mkDirSpec "chezmoi.vim" chezmoiVim {})
          (mkDirSpec "cmp-dap" p.cmp-dap {})
          (mkDirSpec "codecompanion.nvim" p.codecompanion-nvim {
            version = "^19.0.0";
            dependencies = ["plenary.nvim" "nvim-treesitter"];
            opts = {};
          })
          (mkDirSpec "crates.nvim" p.crates-nvim {})
          (mkDirSpec "friendly-snippets" p.friendly-snippets {})
          (mkDirSpec "lazydev.nvim" p.lazydev-nvim {})
          (mkDirSpec "gitsigns.nvim" p.gitsigns-nvim {})
          (mkDirSpec "gopher.nvim" gopher {})
          (mkDirSpec "guess-indent.nvim" p.guess-indent-nvim {})
          (mkDirSpec "heirline.nvim" p.heirline-nvim {})
          (mkDirSpec "image.nvim" p.image-nvim {
            build = false;
            opts = {
              backend = "kitty";
              processor = "magick_cli";
              integrations = {
                markdown = {
                  enabled = true;
                  clear_in_insert_mode = false;
                  download_remote_images = true;
                  only_render_image_at_cursor = true;
                  only_render_image_at_cursor_mode = "popup";
                  filetypes = ["markdown" "vimwiki"];
                };
                neorg = {
                  enabled = true;
                  filetypes = ["norg"];
                };
              };
              max_width = null;
              max_height = null;
              max_width_window_percentage = null;
              max_height_window_percentage = 50;
              window_overlap_clear_enabled = false;
              hijack_file_patterns = ["*.png" "*.jpg" "*.jpeg" "*.gif" "*.webp" "*.avif"];
            };
          })
          (mkDirSpec "mason.nvim" p.mason-nvim {})
          (mkDirSpec "mason-lspconfig.nvim" p.mason-lspconfig-nvim {})
          (mkDirSpec "mason-null-ls.nvim" p.mason-null-ls-nvim {})
          (mkDirSpec "mason-nvim-dap.nvim" p.mason-nvim-dap-nvim {})
          (mkDirSpec "mini.icons" p.mini-icons {})
          (mkDirSpec "LuaSnip" p.luasnip {})
          (mkDirSpec "mini.map" p.mini-map {
            event = ["VeryLazy"];
            keys = [
              (inline ''{ "<Leader>um", function() require("mini.map").toggle() end, desc = "Toggle minimap" }'')
              (inline ''{ "<Leader>uM", function() require("mini.map").toggle_focus() end, desc = "Focus minimap" }'')
            ];
            config = inline ''              function(_, opts)
                          local mini_map = require "mini.map"
                          opts.integrations = {
                            mini_map.gen_integration.builtin_search(),
                            mini_map.gen_integration.diagnostic(),
                            mini_map.gen_integration.gitsigns(),
                          }
                          opts.window = { focusable = true, side = "right", width = 10, winblend = 25 }
                          mini_map.setup(opts)
                          mini_map.open()
                        end'';
          })
          (mkDirSpec "neo-tree.nvim" p.neo-tree-nvim {
            opts.filesystem.filtered_items = {
              hide_dotfiles = false;
              hide_gitignored = false;
            };
            init = inline ''              function()
                          vim.api.nvim_create_autocmd("VimEnter", {
                            callback = function() vim.schedule(function() vim.cmd "Neotree show" end) end,
                          })
                        end'';
          })
          (mkDirSpec "nvim-treesitter" treesitter {})
          (mkDirSpec "nvim-treesitter-textobjects" p.nvim-treesitter-textobjects {})
          (mkDirSpec "nvim-ts-autotag" p.nvim-ts-autotag {})
          (mkDirSpec "nvim-web-devicons" p.nvim-web-devicons {})
          (mkDirSpec "nvim-autopairs" p.nvim-autopairs {})
          (mkDirSpec "nvim-dap" p.nvim-dap {})
          (mkDirSpec "nvim-dap-go" p.nvim-dap-go {})
          (mkDirSpec "nvim-dap-python" p.nvim-dap-python {})
          (mkDirSpec "nvim-dap-ui" p.nvim-dap-ui {})
          (mkDirSpec "nvim-highlight-colors" p.nvim-highlight-colors {})
          (mkDirSpec "nvim-lsp-file-operations" p.nvim-lsp-file-operations {})
          (mkDirSpec "nvim-lspconfig" p.nvim-lspconfig {})
          (mkDirSpec "nvim-nio" p.nvim-nio {})
          (mkDirSpec "nvim-vtsls" p.nvim-vtsls {})
          (mkDirSpec "nvim-window-picker" p.nvim-window-picker {})
          (mkDirSpec "none-ls.nvim" p.none-ls-nvim {})
          (mkDirSpec "nui.nvim" p.nui-nvim {})
          (mkDirSpec "package-info.nvim" p.package-info-nvim {})
          (mkDirSpec "plenary.nvim" p.plenary-nvim {})
          (mkDirSpec "resession.nvim" p.resession-nvim {
            opts = resessionOpts;
            config = inline ''
              function(_, opts)
                require("resession").setup(opts)
              end
            '';
          })
          (mkDirSpec "rustaceanvim" p.rustaceanvim {})
          (mkDirSpec "smart-splits.nvim" p.smart-splits-nvim {})
          (mkDirSpec "snacks.nvim" p.snacks-nvim {})
          (mkDirSpec "todo-comments.nvim" p.todo-comments-nvim {})
          (mkDirSpec "toggleterm.nvim" p.toggleterm-nvim {})
          (mkDirSpec "tsc.nvim" p.tsc-nvim {})
          (mkDirSpec "schemastore.nvim" schemastore {})
          (mkDirSpec "venv-selector.nvim" p.venv-selector-nvim {})
          (mkDirSpec "which-key.nvim" p.which-key-nvim {})
          (inline ''{ "WhoIsSethDaniel/mason-tool-installer.nvim", enabled = false }'')
        ]
        ++ communityImports
        ++ [
          (inline ''{ "mason-org/mason.nvim", enabled = false }'')
          (inline ''{ "mason-org/mason-lspconfig.nvim", enabled = false }'')
          (inline ''{ "jay-babu/mason-null-ls.nvim", enabled = false }'')
          (inline ''{ "jay-babu/mason-nvim-dap.nvim", enabled = false }'')
          (inline ''{ "WhoIsSethDaniel/mason-tool-installer.nvim", enabled = false }'')
          (inline ''            {
                        "AstroNvim/astrocore",
                        opts = function(_, opts)
                          opts.treesitter.ensure_installed = {}
                          opts.treesitter.auto_install = false
                          return opts
                        end,
                      }'')
        ];

      lazyOptions = {
        install.colorscheme = ["astrotheme" "habamax"];
        ui.backdrop = 100;
        performance.rtp.disabled_plugins = [
          "gzip"
          "netrwPlugin"
          "tarPlugin"
          "tohtml"
          "zipPlugin"
        ];
      };
    in {
      config.vim = {
        viAlias = true;
        vimAlias = true;
        globals = {
          mapleader = " ";
          maplocalleader = ",";
        };
        opts = {
          number = true;
          relativenumber = false;
          expandtab = true;
          shiftwidth = 0;
          tabstop = 2;
        };

        treesitter = {
          enable = true;
          grammars = grammarPackages;
        };

        lazy = {
          enable = false;
          enableLznAutoRequire = false;
        };

        startPlugins =
          [
            p.lazy-nvim
            treesitter
            grammarBundle
            astronvim
            astrocommunity
          ]
          ++ grammarPackages;

        extraPackages = with pkgs; [
          ansible
          ansible-language-server
          ansible-lint
          astro-language-server
          autotools-language-server
          bash-language-server
          cargo
          clang-tools
          clojure-lsp
          cmake-language-server
          curl
          deadnix
          dockerfile-language-server
          elixir-ls
          fish-lsp
          git
          gleam
          go
          gopls
          glsl_analyzer
          haskell-language-server
          imagemagick
          jdt-language-server
          jinja-lsp
          just-lsp
          kotlin-language-server
          lemminx
          lua-language-server
          luarocks
          nixd
          nodejs
          oxlint
          prettier
          python3
          python3Packages.pip
          python3Packages.virtualenv
          ruby
          ruby-lsp
          ruff
          rust-analyzer
          rustc
          shellcheck
          shfmt
          sqls
          statix
          stylua
          svelte-language-server
          taplo
          terraform-ls
          texlab
          tree-sitter
          tinymist
          ty
          typescript-language-server
          unzip
          vscode-langservers-extracted
          wget
          zls
        ];

        luaConfigRC.astronvimClipboard = inputs.nvf.lib.nvim.dag.entryAnywhere ''
          vim.g.clipboard = "osc52"
        '';

        luaConfigRC.astronvim = inputs.nvf.lib.nvim.dag.entryAfter ["mappings"] ''
          require("lazy").setup(${toLua pluginSpecs}, ${toLua lazyOptions})
          vim.opt.rtp:prepend("${grammarBundle}")

          local treesitter_group = vim.api.nvim_create_augroup("nix_native_treesitter", { clear = true })
          local enable_treesitter = function(args)
            if vim.bo[args.buf].filetype ~= "" then pcall(vim.treesitter.start, args.buf) end
          end
          vim.api.nvim_create_autocmd("FileType", {
            group = treesitter_group,
            callback = enable_treesitter,
          })
          for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
            enable_treesitter { buf = bufnr }
          end

          require("resession").setup(${toLua resessionOpts})
        '';
      };
    };

    perSystem = {pkgs, ...}: {
      packages.nvim-astronvim =
        (inputs.nvf.lib.neovimConfiguration {
          inherit pkgs;
          modules = [self.neovimModules.astronvim];
        }).neovim;
    };
  };
}
