---
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-fallarbor:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: alyraffauf
      - name: Build fallarbor
        run: >-
          nix build --accept-flake-config --print-out-paths
          .#nixosConfigurations.fallarbor.config.system.build.toplevel
  build-rustboro:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: alyraffauf
      - name: Build rustboro
        run: >-
          nix build --accept-flake-config --print-out-paths
          .#nixosConfigurations.rustboro.config.system.build.toplevel
  build-sootopolis:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: alyraffauf
      - name: Build sootopolis
        run: >-
          nix build --accept-flake-config --print-out-paths
          .#nixosConfigurations.sootopolis.config.system.build.toplevel
name: build-nixos
'on':
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - _img/**
  workflow_dispatch: {}
