name: build-nix
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    paths:
      - "pkgs/**"
      - "flake.nix"
      - "flake.lock"
  workflow_dispatch:
jobs:
  build-deployer:
    runs-on: native
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Setup Cachix
        run: cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build deployer package
        run: nix build --accept-flake-config .#packages.x86_64-linux.deployer --no-link --print-out-paths | cachix push alyraffauf
  build-formatter:
    runs-on: native
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Setup Cachix
        run: cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build formatter package
        run: nix build --accept-flake-config .#packages.x86_64-linux.formatter --no-link --print-out-paths | cachix push alyraffauf
  build-installer:
    runs-on: native
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Setup Cachix
        run: cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build installer package
        run: nix build --accept-flake-config .#packages.x86_64-linux.installer --no-link --print-out-paths | cachix push alyraffauf
  build-devShell:
    runs-on: native
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Setup Cachix
        run: cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build devShell
        run: nix build --accept-flake-config .#devShells.x86_64-linux.default --no-link --print-out-paths | cachix push alyraffauf
