concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-aly-pacifidlog:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 1
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: alyraffauf
    - name: Build aly@pacifidlog
      run: nix build --accept-flake-config --print-out-paths .#homeConfigurations.aly@pacifidlog.activationPackage
name: build-home-manager
'on':
  push:
    paths-ignore:
    - '**/*.md'
    - .github/**
    - _img/**
  workflow_dispatch: {}
