name: build-darwin
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    paths-ignore:
      - "**/*.md"
      - ".github/**"
      - "_img/**"
  workflow_dispatch:
jobs:
  build-fortree:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@master
        with:
          name: alyraffauf
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build fortree
        run: nix build --accept-flake-config --print-out-paths .#darwinConfigurations.fortree.config.system.build.toplevel
