concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-fortree:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 1
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: alyraffauf
    - name: Build fortree
      run: nix build --accept-flake-config --print-out-paths .#darwinConfigurations.fortree.config.system.build.toplevel
name: build-darwin
'on':
  push:
    paths-ignore:
    - '**/*.md'
    - .github/**
    - _img/**
  workflow_dispatch: {}
