name: deploy-tailscale-acls

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/deploy-tailscale-acls.yml"
      - "tailscale.nix"
  pull_request:
    branches: ["master"]
    paths:
      - ".github/workflows/deploy-tailscale-acls.yml"
      - "tailscale.nix"
  workflow_dispatch:
    inputs:
      action:
        description: "Which action to run"
        required: true
        type: choice
        default: deploy
        options:
          - deploy
          - test

jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Convert tailscale.nix to tailscale.json
        run: nix eval --json -f tailscale.nix > tailscale.json

      - name: Deploy ACL
        if: >
          github.event_name == 'push'
          || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy')
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ secrets.TS_API_KEY }}
          tailnet: ${{ secrets.TS_TAILNET }}
          policy-file: tailscale.json
          action: apply

      - name: Test ACL
        if: >
          github.event_name == 'pull_request'
          || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'test')
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ secrets.TS_API_KEY }}
          tailnet: ${{ secrets.TS_TAILNET }}
          policy-file: tailscale.json
          action: test
