name: update-inputs
on:
  schedule:
    - cron: "0 6 * * 2,5"
  workflow_dispatch:
jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
      - name: Setup Git
        run: |
          git config --local user.name  "github-actions[bot]"
          git config --local user.email  "github-actions[bot]@users.noreply.github.com"
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.FLAKE_UPDATE_PAT }}
          pr-title: "flake: update inputs"
          pr-assignees: alyraffauf
          pr-labels: |-
            dependencies
            automated
